name: Validate Extensions

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('global.json', 'source/**/*.csproj') }}

      - name: 'Run: GenerateManifest'
        run: ./build.cmd GenerateManifest